import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
const source=await readFile(new URL('../web/local-state.js',import.meta.url),'utf8');
const clone=value=>JSON.parse(JSON.stringify(value));
function server(){const records=new Map(),calls=[];let serial=0;return {records,calls,async api(action,args){calls.push({action,...clone(args)});const old=records.get(args.key)||{key:args.key,value:null,revision:0};if(action==='state_get')return clone(old);assert.equal(action,'state_put');if(args.expected_revision!==old.revision){const error=new Error('Conflict');error.status=409;throw error;}const result={key:args.key,value:clone(args.value),revision:(++serial).toString(16).padStart(64,'0')};records.set(args.key,result);return clone(result);}};}
function client(remote,{legacy=new Map(),api=remote.api}={}){const errors=[],events=[],window={crypto:webcrypto,localStorage:{getItem:key=>legacy.get(key)??null,removeItem:key=>legacy.delete(key),setItem(){throw new Error('Browser writes are forbidden');}}};vm.runInNewContext(source,{window,TextEncoder});const store=window.PaperLibraryLocalState.create({api,onError:(...args)=>errors.push(args)});store.subscribe(event=>events.push(event));return {store,errors,events};}
test('client durable values survive a new browser and working-cache eviction',async()=>{const remote=server(),a=client(remote);for(let i=0;i<40;i++)await a.store.put(`chat:paper-${i}`,{draft:`Question ${i}`});const b=client(remote);assert.deepEqual(clone(await b.store.get('chat:paper-0')),{draft:'Question 0'});assert.equal(remote.records.size,40);});
test('client same-key writes coalesce and patches preserve independent preference fields',async()=>{const remote=server(),a=client(remote);await a.store.get('preferences');await Promise.all([a.store.patch('preferences',{model:'synthetic/model'}),a.store.patch('preferences',{'reading-panel-side':'right'}),a.store.patch('preferences',{'auto-feedback':true})]);assert.deepEqual(clone(await a.store.get('preferences')),{model:'synthetic/model','reading-panel-side':'right','auto-feedback':true});const writes=remote.calls.filter(c=>c.action==='state_put');assert.ok(writes.length<=2);for(let i=1;i<writes.length;i++)assert.notEqual(writes[i].expected_revision,writes[i-1].expected_revision);});
test('client cross-browser conflicts retain exportable local text without overwriting remote state',async()=>{const remote=server(),a=client(remote),b=client(remote);await a.store.put('chat:paper-a',{draft:'Initial'});await b.store.get('chat:paper-a');await a.store.put('chat:paper-a',{draft:'Browser A'});await assert.rejects(b.store.put('chat:paper-a',{draft:'Browser B'}),/另一浏览器/);assert.equal(remote.records.get('chat:paper-a').value.draft,'Browser A');assert.equal((await b.store.get('chat:paper-a')).draft,'Browser B');assert.equal(b.store.status('chat:paper-a').status,'conflict');assert.equal(b.store.exportPending()[0].value.draft,'Browser B');await assert.rejects(b.store.flush(),/另一浏览器/);assert.equal(remote.records.get('chat:paper-a').value.draft,'Browser A');});
test('client lost responses are confirmed through exact readback without duplicating a write',async()=>{const remote=server();let lose=true;const a=client(remote,{api:async(action,args)=>{const result=await remote.api(action,args);if(action==='state_put'&&lose){lose=false;throw new Error('Lost response');}return result;}});await a.store.put('reader',{paperId:'paper-a'});assert.equal(remote.calls.filter(value=>value.action==='state_put').length,1);assert.equal(a.store.status('reader').status,'saved');});
test('client explicit retry saves retained failed writes and clears the failure status',async()=>{const remote=server();let offline=true;const a=client(remote,{api:async(action,args)=>{if(action==='state_put'&&offline)throw new Error('Offline');return remote.api(action,args);}});await assert.rejects(a.store.put('metadata:paper-a',{title:'Unsaved'}),/Offline/);assert.equal((await a.store.get('metadata:paper-a')).title,'Unsaved');offline=false;await a.store.retry('metadata:paper-a');assert.equal(a.store.status('metadata:paper-a').status,'saved');assert.equal(a.store.status('metadata:paper-a').error,null);});
test('first-read outages retain an exportable candidate and never overwrite previously unseen remote content',async()=>{const remote=server();let offline=true;const a=client(remote,{api:async(action,args)=>{if(offline)throw new Error('Disconnected');return remote.api(action,args);}});await assert.rejects(a.store.put('chat:paper-a',{draft:'Local candidate'}));assert.equal(a.store.exportPending()[0].value.draft,'Local candidate');await remote.api('state_put',{key:'chat:paper-a',value:{draft:'Existing remote'},expected_revision:0});offline=false;await assert.rejects(a.store.retry('chat:paper-a'),/另一浏览器/);assert.equal(remote.records.get('chat:paper-a').value.draft,'Existing remote');});
test('legacy migration verifies service writes before removing only known browser keys',async()=>{const remote=server(),legacy=new Map([['paper-library:synthetic:model','synthetic/model'],['paper-library:synthetic:paper-drafts-v2',JSON.stringify([['paper-a',{draft:'Old draft',annotationRefs:[]}]])],['paper-library:reading-panel-side:v1','right'],['unrelated-private-key','untouched']]);const a=client(remote,{legacy});const result=await a.store.migrateLegacy(()=>'synthetic');assert.equal(result.migrated,3);assert.deepEqual([...legacy.keys()],['unrelated-private-key']);assert.equal((await a.store.get('chat:paper-a')).draft,'Old draft');assert.equal((await a.store.get('preferences'))['reading-panel-side'],'right');});
test('legacy migration backs up conflicts on the service without resurrecting a cleared host draft',async()=>{for(const remoteValue of [{draft:'New host'},null]){const remote=server(),legacy=new Map([['paper-library:synthetic:paper-drafts-v2',JSON.stringify([['paper-a',{draft:'Old browser'}]])]]);await remote.api('state_put',{key:'chat:paper-a',value:remoteValue,expected_revision:0});const a=client(remote,{legacy});const result=await a.store.migrateLegacy('synthetic');assert.equal(result.retained,0);assert.equal(result.backedUp,1);assert.equal(legacy.size,0);assert.deepEqual(remote.records.get('chat:paper-a').value,remoteValue);const backup=[...remote.records.values()].find(record=>record.key.startsWith('migration:'));assert.deepEqual(backup.value.value,[['paper-a',{draft:'Old browser'}]]);assert.ok(a.errors.length);}});
test('client lifecycle flush covers a write submitted immediately before it',async()=>{const remote=server(),a=client(remote);const pending=a.store.put('reader',{paperId:'paper-a'});await a.store.flush({keepalive:true});assert.equal(remote.records.get('reader')?.value.paperId,'paper-a');await pending;});
test('legacy preferences respect a host tombstone and keep their old values in verified backups',async()=>{
  const remote=server(),legacy=new Map([['paper-library:synthetic:model','synthetic/old'],['paper-library:reading-panel-side:v1','right']]);
  await remote.api('state_put',{key:'preferences',value:null,expected_revision:0});const a=client(remote,{legacy});
  const result=await a.store.migrateLegacy('synthetic');assert.equal(result.backedUp,2);assert.equal(legacy.size,0);
  assert.equal(remote.records.get('preferences').value,null);assert.equal([...remote.records.keys()].filter(key=>key.startsWith('migration:')).length,2);
});
test('normal small writes already use keepalive and request sizing includes UTF-8 content',async()=>{
  const remote=server(),options=[],a=client(remote,{api:(action,args,opts)=>{if(action==='state_put')options.push(opts);return remote.api(action,args);}});
  await a.store.put('chat:small',{draft:'中文草稿'});await a.store.put('metadata:large',{title:'中'.repeat(21000)});
  assert.equal(options[0].keepalive,true);assert.equal(options[1].keepalive,false);
  await assert.rejects(a.store.put('metadata:oversize',{title:'中'.repeat(90000)}),/256 KiB/);
  assert.equal(remote.records.has('metadata:oversize'),false);
});
